version: '2'

services:

  django:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    command: ./manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ../backend:/usr/src/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    links:
      - django
      - selenium
    ports:
      - "8080:8080"
    # Set HOST_UID in .env file
    user: $HOST_UID
    volumes:
      - .:/usr/src/app
      - dev_cache:/home/node/.cache
    working_dir: /usr/src/app

  selenium:
    image: selenium/standalone-chrome

volumes:
  dev_cache:
