version: '2'

services:

  django:
    build:
      context: ../backend
      args:
        - development=true
    command: ./manage.py runserver 0.0.0.0:8000
    entrypoint: ""
    environment:
      - DJANGO_CONFIGURATION=Dev
    expose:
      - "8000"
    user: $HOST_UID
    volumes:
      - ../backend:/app

  frontend:
    build:
      context: .
      args:
        - node_base=node
        - node_env=development
    command: yarn dev
    environment:
      - NODE_ENV=development
    links:
      - django
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - dev_cache:/home/node/.cache

volumes:
  dev_cache:
