version: '2'

services:

  coverage:
    image: python:3.5-alpine
    command: python -m http.server 8888
    ports:
      - "8888:8888"
    volumes:
      - ./test/unit/coverage/lcov-report:/usr/src/http:ro
    working_dir: /usr/src/http

  django:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    command: ./manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ../backend:/usr/src/app

  frontend:
    build:
      context: .
      args:
        - node_base=node
        - node_env=development
    command: yarn dev
    environment:
      - NODE_ENV=development
    links:
      - django
      - selenium
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - dev_cache:/home/node/.cache

  selenium:
    image: selenium/standalone-chrome

volumes:
  dev_cache:
