FROM node:boron

# Set-up yarn cache directory
RUN set -ex \
        && mkdir -p /home/node/.cache \
        && chown -R node:node /home/node

# Install vue-cli
RUN set -ex \
        && chown root:staff /usr/local/* \
        && adduser node staff \
        && su - node -c "yarn global add vue-cli"
