FROM node:boron

# Install yarn
RUN set -ex \
        && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg \
           | apt-key add - \
        && echo "deb http://dl.yarnpkg.com/debian/ stable main" \
           | tee /etc/apt/sources.list.d/yarn.list \
        && apt-get update \
        && apt-get install --no-install-recommends yarn \
        && rm -rf /var/lib/apt/lists \
        && mkdir -p /home/node/.cache \
        && chown -R node:node /home/node

# Install vue-cli
RUN set -ex \
        && chown root:staff /usr/local/* \
        && adduser node staff \
        && su - node -c "yarn global add vue-cli"
