version: '2'

services:

  django:
    build:
      context: ../backend
      args:
        - development=true
    command: ./manage.py runserver 0.0.0.0:8000
    entrypoint: ""
    environment:
      - DJANGO_CONFIGURATION=Dev
    expose:
      - "8000"
    user: $HOST_UID
    volumes:
      - ../backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
      - PORT=8080
    links:
      - django
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - dev_cache:/home/node/.cache
      - /usr/src/app/node_modules

volumes:
  dev_cache:
